### PR TITLE
Better management of visual icons for cities and text size of cities

### PR DESCRIPTION
**Pull request by kent1D**
Cities with french embassy = black stars, Capital city without french embassy = white stars:

embassies_capitales_stars

Cities with french presence = black square, Cities in general = white square:

cities_with_without_french_presence

Mix of cities and towns at zoom 9:

mix_cities_and_towns_zoom_9

Mix of cities and towns at zoom 11:

mix_cities_and_towns_zoom_11

### CODE REVIEW

**Comment by yohanboniface** [comment]
Much better! :)
I still see a density issue between town and city icons: basically I think we should not change both density/size AND shape, otherwise the icons seems not be on a same referential.
I haven't looked at it in details, but I think a circle must be a bit bigger than a square to appear having the same density.

**Comment by kent1D** [comment]
Should be better now I think : 

capture d ecran 2018-07-06 a 12 24 28
capture d ecran 2018-07-06 a 12 23 10

**Comment by yohanboniface** [comment]
Much better!
Can I be an asshole one last time? :)
Can you try by making the square a bit smaller instead of the circle bigger? Just to compare, and we GOOD! :)

**Comment by yohanboniface** [comment]
Do not commit, just push a screenshot :)

**Comment by kent1D** [comment]
Here it is with the original circle size : 
capture d ecran 2018-07-06 a 12 47 17

And the one actually in the pull request:

capture d ecran 2018-07-06 a 12 49 44

**Comment by yohanboniface** [comment]
Thanks!
I confirm with those screenshot I'd go with the smaller set (smaller with same quality of info == better).
What do you think?

**Comment by kent1D** [comment]
I confirm also with the smaller set : https://github.com/tilery/pianoforte/pull/43/files/833060372a84a942396f029305bb0c96c5092635..1aea01c98021b7a77a7580550ed07a1646438534

**Pull request merged**
